name: CI

on:
  push:
    branches: [ main, feat/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run security audit
        run: npm audit --audit-level moderate
        continue-on-error: false

  quality:
    needs: security
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x, 22.x]
    uses: ./.github/workflows/quality.yml
    with:
      node-version: ${{ matrix.node-version }}

  e2e:
    needs: quality
    uses: ./.github/workflows/e2e.yml
    with:
      node-version: '20.x'
